default:
  # Django Required starting settings
  STATIC_ROOT: staticfiles
  STATIC_URL: /static/
  STATICFILES_STORAGE: whitenoise.storage.CompressedManifestStaticFilesStorage
  INSTALLED_APPS: &default-installed-apps-alias
    - whitenoise.runserver_nostatic
    - django.contrib.admin
    - django.contrib.auth
    - django.contrib.contenttypes
    - django.contrib.sessions
    - django.contrib.messages
    - django.contrib.staticfiles
    - debug_toolbar
    - rest_framework
    - main_backend
  MIDDLEWARE: &default-middleware-alias
    - django.middleware.security.SecurityMiddleware
    - whitenoise.middleware.WhiteNoiseMiddleware
    - django.contrib.sessions.middleware.SessionMiddleware
    - django.middleware.common.CommonMiddleware
    - django.middleware.csrf.CsrfViewMiddleware
    - django.contrib.auth.middleware.AuthenticationMiddleware
    - django.contrib.messages.middleware.MessageMiddleware
    - django.middleware.clickjacking.XFrameOptionsMiddleware
    - debug_toolbar.middleware.DebugToolbarMiddleware
  ROOT_URLCONF: configure.urls
  WSGI_APPLICATION: configure.wsgi.application
  LANGUAGE_CODE: en-us
  TIME_ZONE: UTC
  USE_I18N: true
  USE_L10N: true
  USE_TZ: true
  TEMPLATES:
    - BACKEND: django.template.backends.django.DjangoTemplates
      DIRS: []
      APP_DIRS: true
      OPTIONS:
        context_processors:
          - django.template.context_processors.debug
          - django.template.context_processors.request
          - django.contrib.auth.context_processors.auth
          - django.contrib.messages.context_processors.messages

  # Password validation
  # https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators
  AUTH_PASSWORD_VALIDATORS:
    - NAME: django.contrib.auth.password_validation.UserAttributeSimilarityValidator
    - NAME: django.contrib.auth.password_validation.MinimumLengthValidator
    - NAME: django.contrib.auth.password_validation.CommonPasswordValidator
    - NAME: django.contrib.auth.password_validation.NumericPasswordValidator
  # Database
  # https://docs.djangoproject.com/en/2.0/ref/settings/#databases
  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: db.sqlite3
  INTERNAL_IPS:
    - '127.0.0.1'
    - 'localhost'

development:
    ALLOWED_HOSTS:
        - '*'
    TIME_ZONE: Europe/Helsinki
    DATABASES:
      default:
        ENGINE: django.db.backends.postgresql_psycopg2
        NAME: django_app_boilerplate
        USERNAME: postgres,
        PASSWORD: postgrespw,
        HOST: localhost,
        PORT: 5432,

production:
    ALLOWED_HOSTS:
        - 'PRODUCTION_URL'
    DATABASES:
      default:
        ENGINE: database_engine
        NAME: database_name
        USERNAME: database_username,
        PASSWORD: database_password,
        HOST: database_host,
        PORT: database_port,
